SitioAdmin/Controllers/FuncionarioController.cs
using SitioAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SitioAdmin.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult IndexFuncionario()
        {
            List<BachesVM> objLista = new List<BachesVM>();

            wcfServicio.IwcfExtServiceClient objServicio = new wcfServicio.IwcfExtServiceClient();

            var objResp = objServicio.Listado();

            foreach (var fila in objResp)
            {
                objLista.Add(new BachesVM()
                {
                    IdBache = fila.IdBache,
                    Calle = fila.Calle,
                    Distrito = fila.Distrito,
                    Tamano = fila.Tamano,
                    Posicion = fila.Posicion,
                    Usuario = fila.Usuario,
                    Prioridad = fila.Prioridad,
                    Fcreacion = fila.Fcreacion,
                    Estado = fila.Estado
                });
            }
            return View(objLista);
        }

        //MOSTRAR INFORME DE REPORTE
        public ActionResult InformeDeReporte()
        {
            List<InformeVM> objLista = new List<InformeVM>();

            wcfServicio.IwcfExtServiceClient objServicio = new wcfServicio.IwcfExtServiceClient();

            var objResp = objServicio.ListadoInforme();

            foreach (var fila in objResp)
            {
                objLista.Add(new InformeVM()
                {
                    IdInformeBache = fila.IdInformeBache,
                    Ubicacion = fila.Ubicacion,
                    Tamano = fila.Tamano,
                    Brigada = fila.Brigada,
                    Equipamiento = fila.Equipamiento,
                    HorasDeReparacion = fila.HorasDeReparacion,
                    EstadoBache = fila.EstadoBache,
                    CantRelleno = fila.CantRelleno,
                    CostoBache = fila.CostoBache,
                    IdBache = fila.IdBache,
                });
            }
            return View(objLista);
        }
        //VISTA QUE MUESTRA LOS REPORTES DE DANO
        public ActionResult IndexDano()
        {
            List<DanoVM> objLista = new List<DanoVM>();

            wcfServicio.IwcfExtServiceClient objServicio = new wcfServicio.IwcfExtServiceClient();

            var objResp = objServicio.ListadoDano();

            foreach (var fila in objResp)
            {
                objLista.Add(new DanoVM()
                {
                    IdReporte = fila.IdReporte,
                    TipoDano = fila.TipoDano,
                    CostoReparacion = fila.CostoReparacion,
                    IdUsuario = fila.IdUsuario,
                    IdBache = fila.IdBache,
                    Fcreacion = fila.Fcreacion,
                    Estado = fila.Estado
                });
            }
            return View(objLista);
        }

        // VISTA CREAR INFORME 
        public ActionResult CreateInformeBache()
        {
            return View();
        }
        //CREACION DE INFROME DE REPORTE
        [HttpPost]
        public ActionResult CrearInforme(InformeVM ObjInforme)
        {
            string strTitulo = "⚠ Se ha producido un error ⚠";
            bool boolexitoso = false;
            string strMensaje = "El correo esta ya siendo utilizado...";
            int IdSolicitud = 0;
            if (ModelState.IsValid)
            {
                wcfServicio.IwcfExtServiceClient objServicio = new wcfServicio.IwcfExtServiceClient();
                wcfServicio.InformeVM objReg = new wcfServicio.InformeVM();
                try
                {
                    objReg.Ubicacion = ObjInforme.Ubicacion;
                    objReg.Tamano = ObjInforme.Tamano;
                    objReg.Brigada = ObjInforme.Brigada;
                    objReg.Equipamiento = ObjInforme.Equipamiento;
                    objReg.HorasDeReparacion = ObjInforme.HorasDeReparacion;
                    objReg.EstadoBache = ObjInforme.EstadoBache;
                    objReg.CantRelleno = ObjInforme.CantRelleno;
                    objReg.CostoBache = ObjInforme.CostoBache;
                    objReg.IdBache = ObjInforme.IdBache;

                    var objResp = objServicio.RegistroInforme(objReg);

                    if (objResp.IdRespuesta == 0)
                    {
                        strTitulo = "Solicitud Creada";
                        boolexitoso = true;
                        strMensaje = "La solicitud fue creada satisfactoriamente...";
                        IdSolicitud = objResp.IdSolicitud;

                    }
                    else
                    {
                        strTitulo = "Error al crear la solicitud";
                        boolexitoso = false;
                        strMensaje = objResp.Mensaje;
                        IdSolicitud = 0;
                    }

                }
                catch (Exception ex)
                {
                    strTitulo = "Exepcion Encontrada";
                    boolexitoso = false;
                    strMensaje = "Ocurrio una excepción no esperada... Detalles = " + ex.Message;
                    IdSolicitud = 0;
                }
            }
            var objRes = new { success = boolexitoso, titulo = strTitulo, mensaje = strMensaje, IdSolicitud = IdSolicitud };
            return Json(objRes, JsonRequestBehavior.AllowGet);
        }

    }
}

SitioAdmin/Views/Funcionario/CreateInformeBache.cshtml
@model SitioAdmin.Models.InformeVM
@{
    ViewBag.Title = "Reportar Bache";
    Layout = "~/Views/Shared/_Layout_AdminLTE.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="panel-body">
            <div>
                <div class="box shadow-window box-solid box-warning">
                    <div class="box-header with-border">
                        <h3 class="box-title">Reporte de Bache</h3>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <span style="font-weight: bold;">
                                        @Html.DisplayNameFor(x => x.Ubicacion)
                                    </span>
                                    @Html.TextBoxFor(x => x.Ubicacion, new { @class = "form-control", @placeholder = "Ingrese la Ubicacion..." })
                                </div>
                                <div class="form-group">
                                    <span style="font-weight: bold;">
                                        @Html.DisplayNameFor(x => x.Tamano)
                                    </span>
                                    @Html.TextBoxFor(x => x.Tamano, new { @class = "form-control", @placeholder = "Ingrese el Distrito..." })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <span style="font-weight: bold;">
                                        @Html.DisplayNameFor(x => x.Brigada)
                                    </span>
                                    @Html.TextBoxFor(x => x.Brigada, new { @class = "form-control", @placeholder = "Ingrese la Brigada..." })
                                </div>
                                <div class="form-group">
                                    <span style="font-weight: bold;">
                                        @Html.DisplayNameFor(x => x.Equipamiento)
                                    </span>
                                    @Html.TextBoxFor(x => x.Equipamiento, new { @class = "form-control", @placeholder = "Ingrese la Equipamiento..." })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <span style="font-weight: bold;">
                                        @Html.DisplayNameFor(x => x.HorasDeReparacion)
                                    </span>
                                    @Html.TextBoxFor(x => x.HorasDeReparacion, new { @class = "form-control", @placeholder = "Ingrese las Horas de Reparación..." })
                                </div>
                                <div class="form-group">
                                    <span style="font-weight: bold;">
                                        @Html.DisplayNameFor(x => x.EstadoBache)
                                    </span>
                                    @Html.TextBoxFor(x => x.EstadoBache, new { @class = "form-control", @placeholder = "Ingrese el Estado del Bache..." })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <span style="font-weight: bold;">
                                        @Html.DisplayNameFor(x => x.CantRelleno)
                                    </span>
                                    @Html.TextBoxFor(x => x.CantRelleno, new { @class = "form-control", @placeholder = "Ingrese la Cantidad de Relleno..." })
                                </div>
                                <div class="form-group">
                                    <span style="font-weight: bold;">
                                        @Html.DisplayNameFor(x => x.CostoBache)
                                    </span>
                                    @Html.TextBoxFor(x => x.CostoBache, new { @class = "form-control", @placeholder = "Ingrese el Costo Total de Reparación..." })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <span style="font-weight: bold;">
                                        @Html.DisplayNameFor(x => x.IdBache)
                                    </span>
                                    @Html.TextBoxFor(x => x.IdBache, new { @class = "form-control", @placeholder = "Ingrese el No de Reporte de Bache" })
                                </div>
                            </div>
                            <div class="col-md-12" style="display: flex; justify-content:flex-end; ">
                                <div class="form-group">
                                    <a href="@Url.Action("IndexFuncionario", "Funcionario")" class="btn btn-success float-left" onclick="CrearInformeReporte();">Registrar</a>
                                    <a href="@Url.Action("IndexFuncionario", "Funcionario")" class="btn btn-danger float-left">Cancelar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SitioAdmin/Views/Funcionario/IndexDano.cshtml
@{ ViewBag.Title = "Listado de Reportes de Daño";
    Layout = "~/Views/Shared/_Layout_AdminLTE.cshtml"; }

@model IEnumerable<SitioAdmin.Models.DanoVM>

<div class="row">
    <div class="col-xs-12">
        <div class="panel-body">
            <div>
                <div class="box shadow-window box-solid box-warning">
                    <div class="box-header with-border">
                        <h3 class="box-title">Listado de Daños Reportados</h3>
                    </div>
                    <div class="box-body">
                        <div>
                            <table class="table table-striped" id="dataTables-ListaSolicitudes">
                                <thead>
                                    <tr>
                                        <th style="width:auto">
                                            No. de Reporte de Daño
                                        </th>
                                        <th style="width:auto">
                                            Tipo de daño
                                        </th>
                                        <th style="width:auto">
                                            Nombre
                                        </th>
                                        <th style="width:auto">
                                            Teléfono
                                        </th>
                                        <th style="width:auto">
                                            Costo de Reparación
                                        </th>
                                        <th style="width:auto">
                                            No. de Reporte de Bache
                                        </th>
                                        <th style="width:auto">
                                            Fecha de Creación
                                        </th>
                                        <th style="width:auto">
                                            Estado
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.IdReporte)
                                        </td>

                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.TipoDano)
                                        </td>

                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.IdUsuario)
                                        </td>

                                        <td style="width:auto">
                                            2134
                                        </td>

                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.CostoReparacion)
                                        </td>
                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.IdBache)
                                        </td>

                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.Fcreacion)
                                        </td>

                                        <td style="width:auto">
                                            @if (item.Estado == "Activo")
                                            {
                                                <span class="label label-danger">
                                                    Activo
                                                </span>
                                            }
                                        </td>

                                    </tr>
}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SitioAdmin/Views/Funcionario/IndexFuncionario.cshtml
@{
    ViewBag.Title = "Listado de reportes";
    Layout = "~/Views/Shared/_Layout_AdminLTE.cshtml";
}

@model IEnumerable<SitioAdmin.Models.BachesVM>

<div class="row">
    <div class="col-xs-12">
        <div class="panel-body">
            <div>
                <div class="box shadow-window box-solid box-warning">
                    <div class="box-header with-border">
                        <h3 class="box-title">Listado de Reportes</h3>
                    </div>
                    <div class="box-body">
                        <div>
                            <table class="table table-striped" id="dataTables-ListaSolicitudes">
                                <thead>
                                    <tr>
                                        <th style="width:auto">
                                            No. de Reporte
                                        </th>
                                        <th style="width:auto">
                                            Calle
                                        </th>
                                        <th style="width:auto">
                                            Distrito
                                        </th>
                                        <th style="width:auto">
                                            Tamaño
                                        </th>
                                        <th style="width:auto">
                                            Posición
                                        </th>
                                        <th style="width:auto">
                                            Prioridad
                                        </th>
                                        <th style="width:auto">
                                            Fecha de Creación
                                        </th>
                                        <th style="width:auto">
                                            Estado
                                        </th>
                                        <th style="width:auto">

                                        </th>
                                      
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.IdBache)
                                        </td>

                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.Calle)
                                        </td>

                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.Distrito)
                                        </td>

                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.Tamano)
                                        </td>

                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.Posicion)
                                        </td>

                                        <td style="width:auto">
                                            @if (item.Prioridad == "Importante")
                                            {
                                                <span class="label label-warning">
                                                    Importante
                                                </span>
                                            }
                                            @if (item.Prioridad == "Muy Importante")
                                            {
                                                <span class="label label-danger">
                                                    Muy Importante
                                                </span>
                                            }
                                            @if (item.Prioridad == "Menos Importante")
                                            {
                                                <span class="label label-primary">
                                                    Menos Importante
                                                </span>
                                            }

                                        </td>

                                        <td style="width:auto">
                                            @Html.DisplayFor(modelItem => item.Fcreacion)
                                        </td>

                                        <td style="width:auto">
                                            @if (item.Estado == "Activo")
                                            {
                                                <span class="label label-success">
                                                    Activo
                                                </span>}
                                        </td>

                                        <td style="width:auto" class="text-center">
                                            <a href="@Url.Action("CreateInformeBache", "Funcionario")" class="btn btn-social-icon btn-warning text-sm-center" title="Generar Informe"><i class="fa fa-edit text-sm-center"></i></a>
                                        </td>

                                    </tr>
                                  
                                }
                                    </tbody>
                                </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SitioAdmin/Views/Funcionario/InformeDeReporte.cshtml
@{
    ViewBag.Title = "Listado de reportes";
    Layout = "~/Views/Shared/_Layout_AdminLTE.cshtml";
}

@model IEnumerable<SitioAdmin.Models.InformeVM>

<div class="row">
    <div class="col-xs-12">
        <div class="panel-body">
            <div>
                <div class="box shadow-window box-solid box-warning">
                    <div class="box-header with-border">
                        <h3 class="box-title">Informe de Reportes</h3>
                    </div>
                    <div class="box-body">
                        <div>
                            <table class="table table-striped" id="dataTables-ListaSolicitudes">
                                <thead>
                                    <tr>
                                        <th style="width:auto">
                                            No. de Informe de Reporte
                                        </th>
                                        <th style="width:auto">
                                            Ubicación
                                        </th>
                                        <th style="width:auto">
                                            Tamaño
                                        </th>
                                        <th style="width:auto">
                                            Brigada
                                        </th>
                                        <th style="width:auto">
                                            Equipamiento
                                        </th>
                                        <th style="width:auto">
                                            Horas de Reparación
                                        </th>
                                        <th style="width:auto">
                                            Estado de Bache
                                        </th>
                                        <th style="width:auto">
                                            Cantidad de Relleno
                                        </th>
                                        <th style="width:auto">
                                            Costo de Bache
                                        </th>
                                        <th style="width:auto">
                                            No. De Reporte de Bache
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td style="width:auto">
                                                @Html.DisplayFor(modelItem => item.IdInformeBache)
                                            </td>
                                            <td style="width:auto">
                                                @Html.DisplayFor(modelItem => item.Ubicacion)
                                            </td>
                                            <td style="width:auto">
                                                @Html.DisplayFor(modelItem => item.Tamano)
                                            </td>
                                            <td style="width:auto">
                                                @Html.DisplayFor(modelItem => item.Brigada)
                                            </td>
                                            <td style="width:auto">
                                                @Html.DisplayFor(modelItem => item.Equipamiento)
                                            </td>
                                            <td style="width:auto">
                                                @Html.DisplayFor(modelItem => item.HorasDeReparacion)
                                            </td>
                                            <td style="width:auto">
                                                @Html.DisplayFor(modelItem => item.EstadoBache)
                                            </td>
                                               <td style="width:auto">
                                                @Html.DisplayFor(modelItem => item.CantRelleno)
                                            </td>
                                            <td style="width:auto">
                                                @Html.DisplayFor(modelItem => item.CostoBache)
                                            </td>
                                            <td style="width:auto">
                                                @Html.DisplayFor(modelItem => item.IdBache)
                                            </td>
                                            
                                        </tr>

                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>