SMICISite/Controllers/CiudadanoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMICISite.Models;

namespace SMICISite.Controllers
{
    public class CiudadanoController : Controller
    {
        //LISTADO DE REPORTES
        public ActionResult IndexCiudadano()
        {
            List<BachesVM> objLista = new List<BachesVM>();

            wcfServicio.IwcfExtServiceClient objServicio = new wcfServicio.IwcfExtServiceClient();

            var objResp = objServicio.Listado();

            foreach (var fila in objResp)
            {
                objLista.Add(new BachesVM()
                {
                    IdBache = fila.IdBache,
                    Calle = fila.Calle,
                    Distrito = fila.Distrito,
                    Tamano = fila.Tamano,
                    Posicion = fila.Posicion,
                    Usuario = fila.Usuario,
                    Prioridad = fila.Prioridad,
                    Fcreacion = fila.Fcreacion,
                    Estado = fila.Estado
                });
            }
            return View(objLista);
        }

        //VISTA CREAR REPORTE
        public ActionResult CreateReporte()
        {
            return View();
        }

        //VISTA DAÑOS VEHICULARES
        public ActionResult DanosVehiculares()
        {
            return View();
        }

        //CREACION DE REPORTE
        [HttpPost]
        public ActionResult CrearReporteBache(BachesVM ObjBaches)
        {
            string strTitulo = "⚠ Se ha producido un error ⚠";
            bool boolexitoso = false;
            string strMensaje = "El correo esta ya siendo utilizado...";
            int IdSolicitud = 0;
            if (ModelState.IsValid)
            {
                wcfServicio.IwcfExtServiceClient objServicio = new wcfServicio.IwcfExtServiceClient();
                wcfServicio.BachesVM objReg = new wcfServicio.BachesVM();
                try
                {
                    objReg.Calle = ObjBaches.Calle;
                    objReg.Distrito = ObjBaches.Distrito;
                    objReg.Tamano = ObjBaches.Tamano;
                    objReg.Posicion = ObjBaches.Posicion;

                    var objResp = objServicio.RegistroReporteBache(objReg);

                    if (objResp.IdRespuesta == 0)
                    {
                        strTitulo = "Solicitud Creada";
                        boolexitoso = true;
                        strMensaje = "La solicitud fue creada satisfactoriamente...";
                        IdSolicitud = objResp.IdSolicitud;

                    }
                    else
                    {
                        strTitulo = "Error al crear la solicitud";
                        boolexitoso = false;
                        strMensaje = objResp.Mensaje;
                        IdSolicitud = 0;
                    }

                }
                catch (Exception ex)
                {
                    strTitulo = "Exepcion Encontrada";
                    boolexitoso = false;
                    strMensaje = "Ocurrio una excepción no esperada... Detalles = " + ex.Message;
                    IdSolicitud = 0;
                }
            }
            var objRes = new { success = boolexitoso, titulo = strTitulo, mensaje = strMensaje, IdSolicitud = IdSolicitud };
            return Json(objRes, JsonRequestBehavior.AllowGet);
        }

        //CREACION DE REPORTE DAÑO VEHICULAR
        [HttpPost]
        public ActionResult CrearReporteDano(DanoVM ObjDano)
        {
            string strTitulo = "⚠ Se ha producido un error ⚠";
            bool boolexitoso = false;
            string strMensaje = "El correo esta ya siendo utilizado...";
            int IdSolicitud = 0;
            if (ModelState.IsValid)
            {
                wcfServicio.IwcfExtServiceClient objServicio = new wcfServicio.IwcfExtServiceClient();
                wcfServicio.DanoVM objReg = new wcfServicio.DanoVM();
                try
                {
                    objReg.CostoReparacion = ObjDano.CostoReparacion;
                    objReg.TipoDano = ObjDano.TipoDano;
                    objReg.IdBache = ObjDano.IdBache;

                    var objResp = objServicio.RegistroReporteDano(objReg);

                    if (objResp.IdRespuesta == 0)
                    {
                        strTitulo = "Solicitud Creada";
                        boolexitoso = true;
                        strMensaje = "La solicitud fue creada satisfactoriamente...";
                        IdSolicitud = objResp.IdSolicitud;

                    }
                    else
                    {
                        strTitulo = "Error al crear la solicitud";
                        boolexitoso = false;
                        strMensaje = objResp.Mensaje;
                        IdSolicitud = 0;
                    }

                }
                catch (Exception ex)
                {
                    strTitulo = "Exepcion Encontrada";
                    boolexitoso = false;
                    strMensaje = "Ocurrio una excepción no esperada... Detalles = " + ex.Message;
                    IdSolicitud = 0;
                }
            }
            var objRes = new { success = boolexitoso, titulo = strTitulo, mensaje = strMensaje, IdSolicitud = IdSolicitud };
            return Json(objRes, JsonRequestBehavior.AllowGet);
        }

        //VISTA QUE MUESTRA LOS REPORTES DE DANO
        public ActionResult IndexDano()
        {
            List<DanoVM> objLista = new List<DanoVM>();

            wcfServicio.IwcfExtServiceClient objServicio = new wcfServicio.IwcfExtServiceClient();

            var objResp = objServicio.ListadoDano();

            foreach (var fila in objResp)
            {
                objLista.Add(new DanoVM()
                {
                    IdReporte = fila.IdReporte,
                    TipoDano = fila.TipoDano,
                    CostoReparacion = fila.CostoReparacion,
                    IdUsuario = fila.IdUsuario,
                    IdBache = fila.IdBache,
                    Fcreacion = fila.Fcreacion,
                    Estado = fila.Estado
                });
            }
            return View(objLista);
        }
    }
}

SMICISite/Views/Shared/_Layout_AdminLTE.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/AdminLTEcss")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="hold-transition skin-yellow sidebar-mini">
    <div class="wrapper">
        <header class="main-header">

            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>MOP</b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">M. de Obras Públicas</span>
            </a>

            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <!-- User Account: style can be found in dropdown.less -->
                        <!-- Control Sidebar Toggle Button-->
                        <li class="dropdown user user-menu" style="margin-right:30px;">  
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Jorge Herrera</b><i class="fa fa-user" style="margin-left: 10px;"></i></a>
                            <!-- User Account: style can be found in dropdown.less -->
                            <ul class="dropdown-menu" style="width: 100px">
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div style="display:flex; justify-content: center;">
                                        <a href="@Url.Action("Index", "Home")" class="btn btn-default btn-flat">Cerrar Sesión</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>

            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" style="margin-top: 30px;">
                    <li><a href="@Url.Action("IndexCiudadano", "Ciudadano")"><i class="fa fa-table"></i><span><b>Listado de Baches Reportados</b></span></a></li>
                    <li><a href="@Url.Action("CreateReporte", "Ciudadano")"><i class="fa fa-pencil"></i><span><b>Reportar Bache</b></span></a></li>
                    <li><a href="@Url.Action("IndexDano", "Ciudadano")"><i class="fa fa-table"></i><span><b>Listado de Daños Vehiculares</b></span></a></li>
                    <li><a href="@Url.Action("DanosVehiculares", "Ciudadano")"><i class="fa fa-car"></i><span><b>Reportar Daños Vehiculares</b></span></a></li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <div class="content-wrapper">
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section>
        </div>

        <footer class="main-footer">
            <strong>Copyright &copy; 2020 <a href="https://github.com/PanamaRobin/Lab_IS_II" target="_blank">Ingenieria de Software II</a>.</strong> Derechos Reservados
        </footer>
    </div>

    @Scripts.Render("~/Content/AdminLTEJs")
    @RenderSection("scripts", required: false)
</body>
</html>

SMICISite/Views/Shared/_Layout_AdminLTE_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema MOP</title>
    @Styles.Render("~/Content/AdminLTEcss")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="hold-transition login-page">
    @RenderBody()
    @Scripts.Render("~/Content/AdminLTEJs")
    @RenderSection("scripts", required: false)
</body>
</html>

SMICISite/Views/Shared/_Layout_original.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>